version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql_latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - my-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - gunicorn
  gunicorn:
    image: gunicorn
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: gunicorn
    command: gunicorn --reload --bind 0.0.0.0:8000 --workers 4 "create_app:create_app"
    volumes:
      - ./app:/var/www
    networks:
      my-network:
        aliases:
          - gunicorn-app
    depends_on:
      - db

networks:
  my-network:
