version: '3.1'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - gunicorn
  gunicorn:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: gunicorn
    command: gunicorn --reload --bind 0.0.0.0:8000 --workers 4 "app.create_app:create_app"
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
          - gunicorn-app

networks:
  my-network: